<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="P11-AS-CHSSXC2" name="TestName-MPT_SyncService" tests="11" failures="1" timestamp="27 Nov 2017 15:49:12 GMT" time="35.622" errors="0">
  <testcase name="@AfterClass tearDown" time="0.0" classname="com.altisource.MPT_test.MPT_BulkFilesTest">
    <failure type="java.lang.RuntimeException" message="com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.1 Client was not authenticated
">
      <![CDATA[java.lang.RuntimeException: com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.1 Client was not authenticated

	at com.altisource.framework.SendMailSSLWithAttachment.sendingMail(SendMailSSLWithAttachment.java:118)
	at com.altisource.framework.TestBaseClass.tearDown(TestBaseClass.java:64)
Caused by: com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.1 Client was not authenticated

	at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2114)
	at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1618)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1119)
	at javax.mail.Transport.send0(Transport.java:195)
	at javax.mail.Transport.send(Transport.java:124)
	at com.altisource.framework.SendMailSSLWithAttachment.sendingMail(SendMailSSLWithAttachment.java:112)
	... 25 more
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase name="insertIntoGeneralUserData" time="4.323" classname="com.altisource.MPT_test.insertDataToDbTest"/>
  <testcase name="insertIntoGeneralUserData" time="2.675" classname="com.altisource.MPT_test.insertDataToDbTest"/>
  <testcase name="insertIntoGeneralUserData" time="2.687" classname="com.altisource.MPT_test.insertDataToDbTest"/>
  <testcase name="insertIntoGeneralUserData" time="2.648" classname="com.altisource.MPT_test.insertDataToDbTest"/>
  <testcase name="insertIntoGeneralUserData" time="2.713" classname="com.altisource.MPT_test.insertDataToDbTest"/>
  <testcase name="runSync_ServiceExecutable" time="0.016" classname="com.altisource.MPT_test.Sync_ServiceExecutableTest">
    <failure type="java.lang.AssertionError" message="Something went wrong, while execution of Sync service expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Something went wrong, while execution of Sync service expected [false] but found [true]
	at com.altisource.framework.SoftAsserts.fail(SoftAsserts.java:82)
	at com.altisource.framework.SoftAsserts.failNotEquals(SoftAsserts.java:482)
	at com.altisource.framework.SoftAsserts.assertEquals(SoftAsserts.java:111)
	at com.altisource.framework.SoftAsserts.assertEquals(SoftAsserts.java:274)
	at com.altisource.framework.ProjectUtils.executeSyncService(ProjectUtils.java:128)
	at com.altisource.MPT_test.Sync_ServiceExecutableTest.runSync_ServiceExecutable(Sync_ServiceExecutableTest.java:12)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- runSync_ServiceExecutable -->
  <testcase name="getProjectDetails" time="4.845" classname="com.altisource.MPT_test.MPT_BulkFilesTest"/>
  <testcase name="getProjectDetails" time="1.369" classname="com.altisource.MPT_test.MPT_BulkFilesTest"/>
  <testcase name="getProjectDetails" time="1.333" classname="com.altisource.MPT_test.MPT_BulkFilesTest"/>
  <testcase name="getProjectDetails" time="1.268" classname="com.altisource.MPT_test.MPT_BulkFilesTest"/>
  <testcase name="getProjectDetails" time="1.248" classname="com.altisource.MPT_test.MPT_BulkFilesTest"/>
</testsuite> <!-- TestName-MPT_SyncService -->
